### ISSUE TITLE
Threads are running longer than expected

### ISSUE THREAD

**Issue by joocer** [gva-jjoyce/gva_data#8]
Observing processes running on long jobs, there is an ever-increasing number of threads which suggests the threads are not completing correctly. I suspect the threads which are being observed are the Writer helper thread, although there is code already in place which should passively end these threads (a while loop which should conclude).

**Comment by gva-jjoyce** [comment]
I believe this is because the flag to end the threads is in the __del__ method of the parent class, however, this class is never being garbage collected because the threads have a reference to it.

The flag for the threads to end needs to be set elsewhere, and/or threads need to have another termination condition, such as no writes to the file in an extended period of time.

**Comment by gva-jjoyce** [comment]
Version 0.2 completely rewrites how the writer works, this should be designed out of the solution. In 0.2 there is only one thread which performs this activity across the application rather than one per topic.

**Comment by gva-jjoyce** [comment]
single-threaded version written and regression tests created
